### ISSUE TITLE
Serialization fails with Woodstox and JAXB annotations

### ISSUE THREAD

**Issue by phillipuniverse** [FasterXML/jackson-dataformat-xml#132]
I am trying to get XML serialization via Jackson working. This is the result that I get when I attempt the serialization (actually, with or without Woodstox):

```shell
[artifact:mvn] java.lang.NoSuchMethodError: org.codehaus.stax2.XMLStreamWriter2.writeLong(J)V
[artifact:mvn] 	at com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeNumber(ToXmlGenerator.java:798)
[artifact:mvn] 	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$LongSerializer.serialize(NumberSerializers.java:184)
[artifact:mvn] 	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$LongSerializer.serialize(NumberSerializers.java:175)
[artifact:mvn] 	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575)
[artifact:mvn] 	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:174)
[artifact:mvn] 	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
[artifact:mvn] 	at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:92)
[artifact:mvn] 	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2238)
[artifact:mvn] 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:231)
[artifact:mvn] 	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
[artifact:mvn] 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:161)
[artifact:mvn] 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:101)
```

I am using Spring MVC, and I have it configured like this:

```java
@Configuration
@EnableWebMvc
@ComponentScan("com.mycompany.api")
public class RestApiMvcConfiguration extends WebMvcConfigurerAdapter {

    @Resource(name = "blWrapperOverrideTypeModifier")
    protected WrapperOverrideTypeModifier typeModifier;
    
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        converters.add(new MappingJackson2HttpMessageConverter(getObjectMapper(false)));
        converters.add(new MappingJackson2XmlHttpMessageConverter(getObjectMapper(true)));
    }
    
    protected ObjectMapper getObjectMapper(boolean useXml) {
        Jackson2ObjectMapperBuilder builder = getBuilder();
        TypeFactory factory = TypeFactory.defaultInstance().withModifier(typeModifier);
        if (useXml) {
            return builder.createXmlMapper(true).build().setTypeFactory(factory);
        } else {
            return builder.build().setTypeFactory(factory);
        }
    }
    
    protected Jackson2ObjectMapperBuilder getBuilder() {
        return new Jackson2ObjectMapperBuilder()
            // Ensure JAXB annotations get picked up
            .findModulesViaServiceLoader(true)
            // Enable/disable some features
            .featuresToEnable(new Object[]{DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY})
            .featuresToDisable(new Object[]{SerializationFeature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED});
    }

}
```

These are my dependencies:

```xml
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.5.0</version>
</dependency>
<!-- Add in Jackson's XML converter along with a better  -->
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.5.0</version>
</dependency>
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>woodstox-core-asl</artifactId>
    <version>4.1.4</version>
</dependency>
```

Trying to debug trace this back, and I got to `ToXmlGenerator.java:798` and it is executing `xmlWriter.writeLong(l);`. `_xmlWriter` is of type `RepairingNsStreamWriter`. Weirdly, neither this class nor any of the super classes have the `writeLong` method. I'm not even sure how this compiled in the first place because `BaseStreamWriter` (the top-most superclass of `RepairingNsStreamWriter`) implements `XmlStreamWriter2`. Any advice here?

**Comment by phillipuniverse** [comment]
I found the issue but want to leave this here for Google-ability. The problem was that I was depending on Solr4j, which brought in an older version of the Woodstox dependency and thus an older version of the Stax API (since it bundled it all together). Maven did not catch this, because it looks like the Woodstox dependency changed Maven coordinates (org.codehaus.woodstox:wstx-asl changed to org.codehaus.woodstox:woodstox-core-asl). I ended up with both jars in my lib directory and it defaulted to using the classes from `wstx-asl.jar`.

The fix was to exclude that from Solr like so:

```xml
<dependency>
    <artifactId>solr-solrj</artifactId>
    <groupId>org.apache.solr</groupId>
    <version>4.7.2</version>
    <type>jar</type>
    <scope>compile</scope>
    <exclusions>
        <exclusion>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>wstx-asl</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <artifactId>solr-core</artifactId>
    <groupId>org.apache.solr</groupId>
    <version>4.4.0</version>
    <type>jar</type>
    <scope>compile</scope>
    <exclusions>
        <exclusion>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>wstx-asl</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by cowtowncoder** [comment]
Ah. Yes, I did see from exception that it is a version incompatibility. But it is bit nasty one, due to change in coordinates of Woodstox but not Stax2 (my fault, should have done the same there, back in time).
Thank you for documenting it, in case others bump into it.

**Comment by kingargyle** [comment]
Yep ran into this today with a client running 3.4.1 which didn't have a closeCompletely method that the jackson xml mapping was expecting.  Dealing with legacy code at the client is fun.
