### ISSUE TITLE
Jackson ignores xml root element for abstract class

### ISSUE THREAD

**Issue by davicdsalves** [FasterXML/jackson-dataformat-xml#141]
I am migrating an application from Jersey to Spring MVC and I'm having problems to make Jackson work with the legacy xml's. I receive an abstract object on the request body as follow

---

**MyController.java** 

```
@RequestMapping(method = RequestMethod.PUT, value = ConnectorConstants.SUBSCRIBE_KEY)
public Callable<SubscribeResult> subscribe(
        @PathVariable final String userKey,
        @RequestBody(required = false) final SubscribeRequest subscribeRequest)
{
    return new Callable<SubscribeResult>()
    {
        @Override
        public SubscribeResult call() throws Exception
        {
            return someService.subscribe(userKey, subscribeRequest);
        }
    };
}
```

---

**SubscribeRequest.java**

```
@XmlRootElement(name = "subscribe_request")
@XmlSeeAlso({ OneRequest.class, AnotherRequest.class, SimpleDomainRequest.class })
public abstract class SubscribeRequest implements Request {

    /* (non-Javadoc)
     * @see com.company.client.request.Request#getBody()
     */
    @Override
    public abstract <K, V> Map<K, V> getBody();

    protected final Map<Object, Object> params = new HashMap<Object, Object>();

}
```

---

**SimpleDomainRequest.java**

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "simple_domain_request")
public class SimpleDomainRequest extends SubscribeRequest
{
    ... methods
}
```

---

**AnotherRequest.java**

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "another_request")
public class AnotherRequest extends SubscribeRequest
{
    ... methods
}
```

---

**OneRequest.java**

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "one_request")
public class OneRequest extends SubscribeRequest
{
    ... methods
}
```

---

Here is one of the xml's the controller receives if the type of the object is SimpleDomainRequest:

```
<simple_domain_request>
  <params>
    <entry>
        <key
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">MY KEY
        </key>
        <value
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">MY VALUE
        </value>
    </entry>
  </params>
</simple_domain_request>
```

So except the controller part that was different when using jersey, I got this code working perfectly fine, the jersey controller was deserializing the object 
without a problem. But after migrating to use Spring-MVC and Jackson it simple can't deserialize it. From what I read Jackson doesn't support @XmlSeeAlso so I tried to do the following changes according to the guides that I found on supporting abstract class with jackson:

**SubscribeRequest** 

```
@XmlRootElement(name = "subscribe_request")
@XmlSeeAlso({ OneRequest.class, AnotherRequest.class, SimpleDomainRequest.class })
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
@JsonSubTypes({
    @JsonSubTypes.Type(value = SimpleDomainRequest.class, name = "simple_domain_request"),
    @JsonSubTypes.Type(value = AnotherRequest.class, name = "another_request"),
    @JsonSubTypes.Type(value = OneRequest.class, name = "one_request")
})   
public abstract class SubscribeRequest implements Request {

    /* (non-Javadoc)
     * @see com.company.client.request.Request#getBody()
     */
    @Override
    public abstract <K, V> Map<K, V> getBody();

    @JsonProperty
    protected final Map<Object, Object> params = new HashMap<Object, Object>();

}
```

But I get the following error from Jackson: _Could not resolve type id 'params'_

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'params' into a subtype of [simple type, class com.company.SubscribeRequest]: known type ids = [SubscribeRequest, one_request, simple_domain_request, another_request]
at [Source: java.io.PushbackInputStream@55416df4; line: 4, column: 13]
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeException(DeserializationContext.java:948) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:275) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:100) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:49) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[jackson-databind-2.5.1.jar:2.5.1]
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2662) ~[jackson-databind-2.5.1.jar:2.5.1]
at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:205) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
```

This is my message converters configuration:

```
public class WebConfigurationAdapter extends WebMvcConfigurerAdapter {
@Override
public void configureMessageConverters(List<HttpMessageConverter<?>> converters)
{
    Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
    builder.featuresToEnable(MapperFeature.DEFAULT_VIEW_INCLUSION);
    converters.add(new MappingJackson2HttpMessageConverter(builder.build()));
    converters.add(new MappingJackson2XmlHttpMessageConverter(builder.createXmlMapper(true).build()));
}
```

If I change it to use _UNWRAP_ROOT_VALUE_

```
builder.featuresToEnable(MapperFeature.DEFAULT_VIEW_INCLUSION, DeserializationFeature.UNWRAP_ROOT_VALUE);
```

Then I get this error:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Root name 'params' does not match expected ('SubscribeRequest') for type [simple type, class com.company.SubscribeRequest]
```

If my request body is wrapped in some xml tag then it works:

```
<any_name_here_doesnt_matter>
 <simple_domain_request>
  <params>
    <entry>
        <key
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">MY KEY
        </key>
        <value
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">MY VALUE
        </value>
    </entry>
  </params>
 </simple_domain_request>
</any_name_here_doesnt_matter>
```

Please keep in mind that even thought I have access to the SubscribeRequest class I need to mantain compatibility, so I can't change the xml that I receive.
DEFAULT_VIEW_INCLUSION is there because I use JsonView for other objects.

I might be missing something obvious here so any help is appreciated or if you need to see more of my code.

Pom.xml declaring jackson

```
<properties>
    <woodstox-core-asl.version>4.4.1</woodstox-core-asl.version>
    <jackson.version>2.5.1</jackson.version>
</properties>

    <!-- Jackson -->
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${jackson.version}</version>
    </dependency>
    <dependency>
        <groupId>com.fasterxml.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-xml</artifactId>
        <version>${jackson.version}</version>
    </dependency>
    <dependency>
        <groupId>org.codehaus.woodstox</groupId>
        <artifactId>woodstox-core-asl</artifactId>
        <version>${woodstox-core-asl.version}</version>
    </dependency>
```

Spring version is 4.1.5.

**Comment by cowtowncoder** [comment]
One thing that would help is to create a self-contained test case first, if the problem can be reproduced outside of SpringMVC. This could help determining where the problem occurs.
From quick glance, your annotations and definitions seem correct, at least I did not notice anything obviously problematic.

One guess I have is that perhaps SpringMVC handles root element, so that unwrapping is unnecessary.

As to `@XmlSeeAlso`, it actually should be:

https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/1

supported -- I need to fix javadoc comments. Just make sure to include `jackson-module-jaxb-annotations` for mapper. Although it may not be enough on its own to enable polymorphic handling, so it may be necessary to still include `@JsonTypeInfo`. This could be a flaw come to think of that -- if you want, feel free to file an issue against JAXB annotations module to suggest it should also be used to infer use of JAXB-style polymorphic handling.

**Comment by davicdsalves** [comment]
Thanks for your response.
I didn't include jaxb module because Spring says it only need jackson-dataformat-xml, but I'm going to try it right now and get back to you.

**Comment by davicdsalves** [comment]
Well sadly it didn't work after including `jackson-module-jaxb-annotations`.

**Comment by cowtowncoder** [comment]
Hmmh. That is odd, as code exists and there are unit tests to verify that subtype detection should work as expected.

**Comment by davicdsalves** [comment]
No problem, I'll try to create a project with my configuration, but the code above is everything that I have that is related to that issue, but I might be missing something I guess.

It just seems to be so simple to me, it should check the root element name and use it, but for some reason it just skip it.

**Comment by cowtowncoder** [comment]
What I am saying is that I know nothing about code within Spring, nor have an easy way to reproduce it there. Containers typically do some pre-processing before handing content; or use specific call sequence. So it is not clear (without a test case) whether it's Spring or Jackson that handles the root element.
