### ISSUE TITLE
Fail to deserialize an object including an enum with whitespace

### ISSUE THREAD

**Issue by Ftaghn** [FasterXML/jackson-dataformat-xml#166]
Hello, 

I'm using jackson for the first time, and encountering a problem with deserialization of an XML file generated from a xsd. 

First off, i used JAXB to create the java classes from an xsd document, and this created the following structure (truncated, there are more attributes but this is representative): 

    public class EVENT {

        @XmlElement(name = "DEFINITION", required = true)
        protected EVENT.DEFINITION definition;

        public static class DEFINITION {

            @XmlElement(name = "REQUESTED_CHANNEL", required = true)
            protected List<EVENT.DEFINITION.REQUESTEDCHANNEL> requestedchannel;
            @XmlAttribute(name = "requestType", required = true)
            protected AREQUESTTYPE requestType;

    }

AREQUESTTYPE is an enum which was also created automatically : 

    @XmlType(name = "A_REQUEST_TYPE")
    @XmlEnum
    public enum AREQUESTTYPE {
 
        @XmlEnumValue("FIRST TYPE")
        FIRST_TYPE("FIRST TYPE"),
        @XmlEnumValue("SECOND TYPE")
        SECOND_TYPE("SECOND TYPE");
    }

Please note that the enumvalues have a whiteSpace in the original xsd (on which i have sadly no control), which i suppose is what led JAXB to create them with an underscore instead of the whitespace, and the original name with whitespace as an alias of the enum (in the brackets).

The problem is that when i try to deserialize an xml (corresponding to the xsd structure) i run into an error while deserializing the enum : 

  
    Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct  instance of AREQUESTTYPE from String value  'FIRST TYPE': value not one of declared Enum instance names: [FIRST_TYPE, SECOND_TYPE]
     at [Source: java.io.StringReader@561868a0; line: 6, column: 2] (through reference chain: EVENT["DEFINITION"]->DEFINITION["requestType"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:797)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:127)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:81)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:17)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2146)
	
If i understand well this error, the deserializer does not check for the alias of the enum : it only reads the values "FIRST_TYPE" and "SECOND_TYPE" and does not recognize the alias when the file to deserialize contains "FIRST TYPE". This seems to be confirmed by the fact that adding the underscore in the file to deserialize solve the problem. Unfortunately i am not authorized to change the structure of neither the xsd nor the files to deserialize so this cannot be a viable solution.

Is this issue already known ? Shall i add an annotation somewhere to solve the probleme and force alias reading ? 

If it is not possible do you please have some ideas about a possible workaround ?

Thank you very much for your attention, and have a nice day.

**Comment by cowtowncoder** [comment]
First things first: make sure you have `jackson-module-jaxb-annotations` in use; otherwise JAXB annotations are not understood. XML module does not require their use, but your use case does.

Assuming this is the case, `XmlEnumValue` annotations should be recognized and used; if not, that could be a bug.

**Comment by cowtowncoder** [comment]
At this point I can not reproduce this issue. `XmlEnumValue` should work and there are tests; it would be great to have a unit test that shows how things fail, with JAXB annotation introspector included (XML module itself does not have in-built JAXB annotation support).

**Comment by cloudhuang** [comment]
Maybe didn't register the `JaxbAnnotationModule` for the `ObjectMapper`

```
 mapper.registerModule(new JaxbAnnotationModule());
```
