### ISSUE TITLE
Exception on deserializing empty element with an xsi attribute on non String type.

### ISSUE THREAD

**Issue by chikim79** [FasterXML/jackson-dataformat-xml#184]
#167 fixed the issue with the String type.

It is still happening on a Double type and possibly others.
xsi attribute is giving errors on Double type regardless of the existence of the value.
e.g. xsi:nil="false" with value and xsi:nil="true" with empty value.

```
<a xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
       <b/>  <!-- works fine -->
       <c xsi:nil="false">0920</c> <!-- works fine -->
       <d xsi:nil="true"/> <!-- fixed in 2.7 -->
       <e xsi:nil="false">1.2</c> <!-- throws exception -->
       <f xsi:nil="true"/> <!-- throws exception -->
</a>
```

```
public class A {
    String b;
    String c;
    String d;
    Double e;
    Double f;
    ...
}
```

```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.Double out of START_OBJECT token
 at [Source: /NFL/shield/esb/input/A.xml; line: 5, column: 2] (through reference chain: com.nfl.dm.shield.ingester.stats.domain.A["e"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDouble(StdDeserializer.java:707)
    at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$DoubleDeserializer.deserialize(NumberDeserializers.java:386)
    at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$DoubleDeserializer.deserialize(NumberDeserializers.java:371)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2673)
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this. I hope this can be fixed; there are some special translations done for `String` handling, but it should be possible to figure out something similar for other simple scalar types: numbers, coolean.

**Comment by nyilmaz** [comment]
`BigDecimal` ends up the same. Any updates on this?

`com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.math.BigDecimal out of START_OBJECT token` for;

`<PointsUsedYTL xsi:nil="true"/>`

**Comment by cowtowncoder** [comment]
@nyilmaz PRs welcome.

**Comment by cowtowncoder** [comment]
Created #354 for general support of `xsi:nil`.
