### ISSUE TITLE
NPE from having custom deserialized values in a list

### ISSUE THREAD

**Issue by TeemuStenhammar** [FasterXML/jackson-dataformat-xml#193]
Hello,

I just stumbled upon a really mystical (to me at least) NPE that is huge road block for my progress. I am parsing XML document that has nil values tagged with `<smthg xsi:nil="true"/>`. I followed some advice of creating a custom deserializer and that worked out well. Here is the deserializer classes that I am using:

```java
public abstract class Nillable<C> {

    private final C value;
    private final boolean isNil;

    public Nillable(C value, Boolean isNil) {
        this.value = value;
        this.isNil = isNil;
    }

    public boolean hasValue() {
        return !this.isNil;
    }
}

```

```java
public class NillableFloat extends Nillable<Float> {

    public NillableFloat(Float value, Boolean isNil) {
        super(value, isNil);
    }
}
```

```java
import android.util.Log;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser;

import java.io.IOException;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;

import javax.xml.stream.XMLStreamReader;

public class NillableDeserializer<T extends Nillable<?>> extends JsonDeserializer {

    private final JsonDeserializer delegate;
    private final Class<T> clazz;
    private final Class<?> generic;

    public NillableDeserializer(JsonDeserializer delegate, Class<T> clazz) {
        this.delegate = delegate;
        this.clazz = clazz;

        Type type = clazz.getGenericSuperclass();
        this.generic = (Class<?>) ((ParameterizedType) type).getActualTypeArguments()[0];
    }

    @Override
    public T deserialize(JsonParser jp, DeserializationContext ctxt)
            throws IOException {
        FromXmlParser fxp = (FromXmlParser) jp;

        boolean isNil = false;

        XMLStreamReader reader = fxp.getStaxReader();
        if (reader.isStartElement()) {
            if (reader.getAttributeCount() > 0) {
                String atVal = reader.getAttributeValue("http://www.w3.org/2001/XMLSchema-instance", "nil");
                if (atVal != null) {
                    isNil = Boolean.parseBoolean(atVal);
                }
            }
        }

        Object value = null;
        if (!isNil) {
            value = delegate.deserialize(jp, ctxt);
        } else {
            jp.getValueAsString(); // move forward
        }

        try {
            return this.clazz.getConstructor(this.generic, Boolean.class).newInstance(value, isNil);
        } catch (Exception e) {
            Log.e("NillableDeserializer", "Could not create Nillable " + this.clazz + ". Make sure to have constructor with Boolean isNil!");
        }

        return null;
    }
}
```

```java
import com.fasterxml.jackson.databind.deser.std.NumberDeserializers;

public class NillableNumberDeserializer<T extends Nillable<?>> extends NillableDeserializer<T> {

    public NillableNumberDeserializer(Class<T> nillable, Class<?> primitive) {
        super(NumberDeserializers.find(primitive, primitive.getName()), nillable);
    }
}
```

So, all the classes above do is enable catching that xsi:nil="true" and crudely imitate Java8 Optional (I am working with Android and hence have to cope with Java7).

Now to the issue part. Here is simple test setup to first show that NillableFloats can be read three at a time. Then a test that shows same works within a list if all Nillables have an actual value. Third test shows that having those values set as nil will break with NPE (only last test fails):

```java
private ObjectMapper xmlMapper;

    @Before
    public void setUp() {
        JacksonXmlModule module = new JacksonXmlModule();
        module.addDeserializer(NillableFloat.class, new NillableNumberDeserializer<>(NillableFloat.class, Float.class));

        xmlMapper = new XmlMapper(module)
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    }

    static String NO_LIST = "" +
            "<SimpleWrapper xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">" +
            "  <nillables>" +
            "    <one xsi:nil=\"true\"/>" +
            "    <two xsi:nil=\"true\"/>" +
            "    <three xsi:nil=\"true\"/>" +
            "  </nillables>" +
            "</SimpleWrapper>";

    static String NON_NILS_IN_LIST = "" +
            "<ListWrapper xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">" +
            "  <nillables>" +
            "    <nillable>" +
            "      <one>1.0</one>" +
            "      <two>2.0</two>" +
            "      <three>3.0</three>" +
            "    </nillable>" +
            "  </nillables>" +
            "</ListWrapper>";

    static String NILS_IN_LIST = "" +
            "<ListWrapper xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">" +
            "  <nillables>" +
            "    <nillable>" +
            "      <one xsi:nil=\"true\"/>" +
            "      <two xsi:nil=\"true\"/>" +
            "      <three xsi:nil=\"true\"/>" +
            "    </nillable>" +
            "  </nillables>" +
            "</ListWrapper>";

    @Test
    public void shouldHandleManyNillables() throws IOException {
        SimpleWrapper wrapper = xmlMapper.readValue(NO_LIST, SimpleWrapper.class);
        assertTrue(wrapper.nillables.one.isNil());
    }

    @Test
    public void shouldHandleManyNillableNonNilsInAList() throws IOException {
        ListWrapper wrapper = xmlMapper.readValue(NON_NILS_IN_LIST, ListWrapper.class);
        assertNotNull(wrapper);
    }

    @Test
    public void shouldHandleManyNillableNilsInAList() throws IOException {
        ListWrapper wrapper = xmlMapper.readValue(NILS_IN_LIST, ListWrapper.class);
        assertNotNull(wrapper);
    }

    static class Nillables {
        public NillableFloat one;
        public NillableFloat two;
        public NillableFloat three;
    }

    static class SimpleWrapper {
        public Nillables nillables;
    }

    static class ListWrapper {
        @JacksonXmlElementWrapper(localName = "nillables")
        @JacksonXmlProperty(localName = "nillable")
        public List<Nillables> nillables;
    }
```

I have tried the same with intermediate class and not using wrapper with no avail. Then I tried with Nillables class having lots of values other than Nillables and still, having multiple nil values in xml will break it, but having just one will work.  I know the code might seem a bit hackish, but the point of the first two test cases was trying to show that the hack works :)

Any help would be really appreciated as I cannot move forward without some means to circumvent the NPE.

**Comment by cowtowncoder** [comment]
Could you include stack trace for NPE here?

**Comment by TeemuStenhammar** [comment]
Yeah, my bad. I remembered that I had left stack trace out just after I left pc...

Here is the stack trace that I see:

```java
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.stenhammar.ListWrapper["nillables"]->java.util.ArrayList[3])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:189)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:266)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at com.stenhammar.XmlSampleTest.shouldHandleManyNillableNilsInAList(XmlSampleTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:143)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	... 36 more
```

Also, I tried the same tests with non-Android environment pulling the master branch from Github and there were no issues with the tests above.

**Comment by TeemuStenhammar** [comment]
Yeah, so, as it happens, I was using older version (2.6.3) and after going to maven repo and checking, I changed it to 2.7.3 which fixed the issue. I'll try a bit harder to check everything next time...

**Comment by cowtowncoder** [comment]
@TeemuStenhammar No problem, mostly I am just glad newer version works better!

Also, if at all possible, it would be great if you could check how 2.7.4-SNAPSHOT works: mostly because I hope to release it soon and there are some fixes to XML handling. But what I have noticed is that xml handling is quite fragile, and despite test coverage there tend to be more regressions than I'd like. So, any additional verification would be valuable.

**Comment by TeemuStenhammar** [comment]
@cowtowncoder Yeah, sure, I'll test with that version as the first thing on Monday morning. I'll report issues, if any, here, and if I don't report, then there was none :) I will then revert back to 2.7.3, but if you want me to try again at some point, then just message me and I will.

**Comment by TeemuStenhammar** [comment]
Where can I get that version from? Or is it just the current master?

**Comment by cowtowncoder** [comment]
@TeemuStenhammar that's the current master, I haven't yet switched master to 2.8 for xml module.

**Comment by TeemuStenhammar** [comment]
It was a bit of a hassle to get the maven project dropped in my gradle environment, but it worked with all my tests and test data when I got it there (except that 'two lists with similarly named items' issue that is open). So no problems here :)
