### ISSUE TITLE
JsonMappingException on node without attributes

### ISSUE THREAD

**Issue by mguillet** [FasterXML/jackson-dataformat-xml#225]
Consider the following XMLs:

XML1
```xml
<root>
  <Child attribute="foo">lorem ipsum</Child>
</root>
```

XML2
```xml
<root>
  <Child>lorem ipsum</Child>
</root>
```

The only difference between them is that the second XML has no attribute in the ```Child``` node.

However when I try to read the second XML, this exception is thrown:
```java
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of TestJackson$Child: no String-argument constructor/factory method to deserialize from String value ('lorem ipsum')
 at [Source: java.io.StringReader@1ed4ae0f; line: 1, column: 25] (through reference chain: TestJackson$Root["Child"])

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:432)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
```

Here is my code reading the two XMLs:
```java
XmlMapper mapper = new XmlMapper();
mapper.setPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE);
mapper.registerModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES));

String xmlOK = "<root><Child attribute=\"foo\">lorem ipsum</Child></root>";
mapper.readValue(xmlOK, Root.class);

String xmlKO = "<root><Child>lorem ipsum</Child></root>";
mapper.readValue(xmlKO, Root.class);
```

And here are the POJO classes:
```java
//Root.java
public class Root {

    private final Child child;

    public Root(Child child) {
      this.child = child;
    }

    public Child getChild() {
      return child;
    }
  }

//Child.java
public class Child {

    @JacksonXmlText
    private final String text;

    private final String attribute;

    public Child(String text, String attribute) {
      this.text = text;
      this.attribute = attribute;
    }

    public String getText() {
      return text;
    }

    public String getAttribute() {
      return attribute;
    }
  }
```

Tested and failing with version  from ```2.8.5``` to ```2.8.7```

Note: I believe this could be the same issue than #219 as we share the same error message.

Am I doing something wrong? 

You can find in attachment of this issue, a simple test file regrouping everything to reproduce the issue: [TestJackson225.java.txt](https://github.com/FasterXML/jackson-dataformat-xml/files/816914/TestJackson225.java.txt)

**Comment by cowtowncoder** [comment]
It might be the same issue, but there may be additional problem in POJO: it is missing one of:

1. Setter for `attribute` (`text` is denoted as a property via annotation) OR
2. `@JsonCreator` for 2-argument constructor

since while parameter names are detected (with parameter names), I don't think constructor will be used. Although if the first case does work I am surprised...

**Comment by FireFry** [comment]
@cowtowncoder any progress with the issue? I encountered a similar one on `2.8.7`. Does this really mean that `jackson-dataformat-xml` cannot be used with immutable classes in production because of limitations around `@JacksonXmlText`? Or is there any workaround?

```
import static org.junit.Assert.assertEquals;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlText;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;

public class JacksonXmlTextTest {

  public static final class Root {
    @JacksonXmlProperty(localName = "Child")
    public final Child child;

    public Root(@JacksonXmlProperty(localName = "Child") Child child) {
      this.child = child;
    }
  }

  public static final class Child {
    @JacksonXmlText
    public final String text;

    public Child(@JacksonXmlProperty(localName = " ") String text) {
      this.text = text;
    }
  }

  private ObjectMapper xmlMapper;

  @Before
  public void setup() {
    xmlMapper = new XmlMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
  }

  // NOTE: This test fails!
  @Test
  public void testRoot() throws IOException {
    Root root = xmlMapper.readValue("<Root><Child>Test</Child></Root>", Root.class);
    assertEquals("Test", root.child.text);
  }

  // Adding a random attribute makes test succeed
  @Test
  public void testRootWithAttribute() throws IOException {
    Root root = xmlMapper.readValue("<Root><Child foo=\"bar\">Test</Child></Root>", Root.class);
    assertEquals("Test", root.child.text);
  }

  // Child element is successfully deserialized without random attributes
  @Test
  public void testChildWithoutAttribute() throws IOException {
    Child child = xmlMapper.readValue("<Child>Test</Child>", Child.class);
    assertEquals("Test", child.text);
  }
}
```

**Comment by cowtowncoder** [comment]
@FireFry No progress, have not had time to spend on Open Source projects for a bit now.

**Comment by cowtowncoder** [comment]
It seems to me that addition of constructor:

```java
@JsonCreator
public Child(String text) { .... }
```

should solve this issue. There has been other work to resolve possibly related issues too (wrt text and attribute); at this point I am not sure what else to do here.
