### ISSUE TITLE
`ObjectReader.readValue()` throws unexpected exception `com.ctc.wstx.exc.WstxUnexpectedCharException'

### ISSUE THREAD

**Issue by agyina** [FasterXML/jackson-dataformat-xml#236]
I use version 2.7.0
Method ObjectReader#readValue(...) must throw JsonProcessingException or IOException but in some cases this method throws unexpected exception like com.ctc.wstx.exc.WstxUnexpectedCharException.

I send 

```
<employee>
  <dates>
    <hired>2018-11-01</hired>
    <started>2002-11-05</started>
    <birthday>2002-06-24</birthday>
  </dates>
  
  <username>monicaG&</username>
  <first_name>Monica</first_name>
  <last_name>Geller</last_name>
  <external_id>abc123</external_id>
  <employee_id>456</employee_id>
</employee>
```

username contains & at the end.

```
[com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '<' (code 60) (expected a name start character)
 at [row,col {unknown-source}]: [8,21]
	at com.ctc.wstx.exc.WstxLazyException.throwLazily(WstxLazyException.java:45)
	at com.ctc.wstx.sr.StreamScanner.throwLazyError(StreamScanner.java:720)
	at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3677)
	at com.ctc.wstx.sr.BasicStreamReader.getText(BasicStreamReader.java:858)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream._collectUntilTag(XmlTokenStream.java:363)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream._next(XmlTokenStream.java:317)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream.next(XmlTokenStream.java:162)
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser.nextToken(FromXmlParser.java:477)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
```

**Comment by cowtowncoder** [comment]
Ok that does sound right. But at the same time... may be tricky to resolve, since that is a runtime exception, of type that is not part of core Stax API (and is sent because Stax API does not allow `XMLStreamException` throwing from many places where it should).

Would it possible to include code to reproduce the problem (with XML you indicate)?
