### ISSUE TITLE
Deserialization of `Exception` serialized as XML fails

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-xml#250]
(note: moved from https://github.com/FasterXML/jackson-databind/issues/1695)

Attempts to deserialize XML serialization of `Exception`s fails with:

```java
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Non-numeric token (VALUE_STRING) for property 'lineNumber'
 at [Source: java.io.StringReader@38bc8ab5; line: 1, column: 116] (through reference chain: java.lang.Object[][0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.deser.std.StackTraceElementDeserializer.deserialize(StackTraceElementDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.std.StackTraceElementDeserializer.deserialize(StackTraceElementDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:103)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at jp.mahara.tumblr.Test.main(Test.java:14)
```

**Comment by cowtowncoder** [comment]
Note: actual fix is in `jackson-databind` (to allow "stringified" number). Also fixed in 2.8 branch, for 2.8.10.
