### ISSUE TITLE
Deserialization from XML to polymorphic POJO having List-typed field throws NPE

### ISSUE THREAD

**Issue by ravxz** [FasterXML/jackson-dataformat-xml#255]
I have XMLs which I need to read/write to Java class or its sub-classes. I use Java 8 and Jackson for mapping.

Maven dependency: `com.fasterxml.jackson.dataformat : jackson-dataformat-xml : 2.9.0` (or any older version).

Base Java class:
```
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=JsonTypeInfo.As.PROPERTY,
              property="type", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = AA.class, name="AA")
})
@JacksonXmlRootElement(localName = "a")
public class A {

    @JsonProperty("type")
    @JacksonXmlProperty(localName = "type")
    private String type;

    // getters, setters
}
```
Child class:
```
public class AA extends A {

    @JsonProperty("b")
    @JacksonXmlElementWrapper(localName = "b", useWrapping = false)
    private List<B> listB = new ArrayList<>();

    // getters, setters
```
Aggregated class:
```
public class B {

    @JsonProperty("bb")
    @JacksonXmlProperty(localName = "bb", isAttribute = true)
    private String bb;

    @JsonProperty("value")
    @JacksonXmlText
    private String value;

    // getters, setters
```
The JUnit test which writes / reads XML document:
```
public class Tester {
    @Test
    public void test() throws IOException {
        ObjectMapper mapper = new XmlMapper().enable(SerializationFeature.INDENT_OUTPUT);

        AA aa = new AA();
        aa.setType("AA");
        aa.setListB(new ArrayList<>());
        aa.getListB().add(new B());
        aa.getListB().get(0).setBb("value");
        aa.getListB().get(0).setValue("value");

        String result = mapper.writeValueAsString(aa);
        System.out.println(result);

        mapper.readValue(result, A.class);
    }
}
```
Test generates output having redundant xml attribute `type` in element `<a>`:
```
<a type="AA">
  <type>AA</type>
  <b bb="value">value</b>
</a>
```
and fails with NullPointerException when parsing the generated xml:
```
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: AA["b"]->java.util.ArrayList[2])

	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1156)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at IssueTest.test(IssueTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTextDeserializer.deserialize(XmlTextDeserializer.java:96)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	... 36 more
```
The issue is also reproducable on older versions (<2.9.0).

**Comment by ravxz** [comment]
The workaround for the issue is using "useWrapping = true" with wrapper element.

**Comment by cowtowncoder** [comment]
Can not reproduce at this point, closing.
