### ISSUE TITLE
Cannot deserialize unwrapped List

### ISSUE THREAD

**Issue by scottsteen** [FasterXML/jackson-dataformat-xml#256]
I'm trying to deserialize xml that contains unwrapped collections of complex objects as `List`s, but Jackson seems to skip a level as if the wrapping tag existed, causing the mapping to fail. If I use a wrapping tag, then this scenario behaves as expected.

XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<Object>
    <LevelOne> <!-- This is an array element -->
        <LevelTwo>
            <Field1>Value1</Field1>
            <Field2>Value2</Field2>
        </LevelTwo>
    </LevelOne>
</Object>
```
Model:
```
public class ExampleObject {
    private List<LevelOne> levelOne;
    // getter and setter

    public static class LevelOne {
        private LevelTwo levelTwo;
        // getter and setter
    }

    public static class LevelTwo {
        private String fieldOne;
        private String fieldTwo;
        // getters and setters
    }
}
```
Module:
```
public class ExampleObjectModule extends JacksonXmlModule {
    @Override
    public void setupModule(SetupContext context) {
        context.setMixInAnnotations(ExampleObject.class, ExampleObjectMixin.class);
        context.setMixInAnnotations(ExampleObject.LevelOne.class, LevelOneMixin.class);
        context.setMixInAnnotations(ExampleObject.LevelTwo.class, LevelTwoMixin.class);
    }

    @JacksonXmlRootElement(localName = "Object")
    static abstract class ExampleObjectMixin {
        @JacksonXmlElementWrapper(useWrapping = false)
        @JacksonXmlProperty(localName = "LevelOne")
        abstract List<ExampleObject.LevelOne> getLevelOne();

        @JacksonXmlElementWrapper(useWrapping = false)
        @JsonProperty("LevelOne") // This is a workaround to set the element name, @JacksonXmlProperty seems to get ignored
        abstract void setLevelOne(List<ExampleObject.LevelOne> levelOne);
    }

    static abstract class LevelOneMixin {
        @JacksonXmlProperty(localName = "LevelTwo")
        abstract ExampleObject.LevelTwo getLevelTwo();

        @JsonProperty("LevelTwo")
        abstract void setLevelTwo(ExampleObject.LevelTwo levelTwo);
    }

    static abstract class LevelTwoMixin {
        @JacksonXmlProperty(localName = "Field1")
        abstract String getFieldOne();

        @JsonProperty("Field1")
        abstract void setFieldOne(String fieldOne);

        @JacksonXmlProperty(localName = "Field2")
        abstract String getFieldTwo();

        @JsonProperty("Field2")
        abstract void setFieldTwo(String fieldTwo);
    }
}
```
Test class:
```
public class ExampleTest {
    public static void main(String[] args) throws Exception {
        ExampleObject object = newObjectReader().readValue(getExampleXml());
        System.out.println(object);
    }

    private static ObjectReader newObjectReader() {
        return new XmlMapper(new ExampleObjectModule()).readerFor(ExampleObject.class);
    }

    private static String getExampleXml() {
        // return the xml described above
    }
}
```
Exception:
> Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Field1" (class com.ExampleObject$LevelOne), not marked as ignorable (one known property: "LevelTwo"])
 at [Source: (StringReader); line: 5, column: 36] (through reference chain: com.ExampleObject["LevelOne"]->java.util.ArrayList[0]->com.ExampleObject$LevelOne["Field1"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1216)

I have walked through the code, and it seems that it finds the `START_ARRAY` element (the LevelOne tag) then skips two tokens, bypassing the LevelTwo tag. This then causes the deserializer to attempt to map Field1 to LevelOne, which does not exist.

I'm not sure if this may be part of a larger xml deserialization issue, given that `@JacksonXmlProperty` is ignored also. Are the xml specific tags designed to be used during deserialization? Or am I not configuring something correctly?

Unfortunately, I cannot switch to wrapped arrays, as this is an attempt to move to Jackson for existing APIs.

Tested against current version (2.9.0)

Thanks.

**Comment by andrey-cabonline** [comment]
I'm having the same issue. Would be glad if someone could hint for any workaround.

**Comment by cowtowncoder** [comment]
I can not reproduce this with 2.11(.1): likely fixed by one of recent changes to handling of nested lists: not sure if it's for 2.11.0 already or only upcoming 2.11.1.
