### ISSUE TITLE
NPE after overriding map serializer with custom implementation (XmlBeanSerializerModifier.modifyMapSerializer)

### ISSUE THREAD

**Issue by agabrys** [FasterXML/jackson-dataformat-xml#259]
Hi,
I'm trying to serialize empty lists and arrays as empty node instead of default "missing" node behavior (why? read here: https://stackoverflow.com/q/46001938/4944847). One of my tries are based on overriding serializers:

    final SimpleModule module = new SimpleModule();
    module.setSerializerModifier(new XmlBeanSerializerModifier() {
        // ...
        @Override
        public JsonSerializer<?> modifyMapSerializer(SerializationConfig config, MapType valueType, BeanDescription beanDesc,
                    JsonSerializer<?> serializer) {
            final JsonSerializer<?> modifiedSerializer = super.modifyMapSerializer(config, valueType, beanDesc, serializer);
            return new PrintEmptyElementsJsonSerializer(modifiedSerializer, o -> ((Map<?, ?>) o).isEmpty());
        }
        // ...
    }

Unfortunately after adding that code Jackson XML core always throws NPE.

    com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.Arrays$ArrayList[0]->biz.gabrys.adam.bugsreports.jackson.xml.emptyelementsserialization.commons.ReportView["payload"]->java.util.LinkedHashMap["text"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:721)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
        at biz.gabrys.adam.bugsreports.jackson.xml.emptyelementsserialization.v289.SerializerModifierXmlSerializer$PrintEmptyElementsJsonSerializer.serialize(SerializerModifierXmlSerializer.java:88)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:202)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at biz.gabrys.adam.bugsreports.jackson.xml.emptyelementsserialization.v289.SerializerModifierXmlSerializer$PrintEmptyElementsJsonSerializer.serialize(SerializerModifierXmlSerializer.java:88)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:105)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
        at biz.gabrys.adam.bugsreports.jackson.xml.emptyelementsserialization.commons.AbstractXmlSerializer.toXml(AbstractXmlSerializer.java:14)
        at biz.gabrys.adam.bugsreports.jackson.xml.emptyelementsserialization.commons.XmlSerializerTest.testToXml(XmlSerializerTest.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
    Caused by: java.lang.NullPointerException
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:707)
        ... 39 more

I found that when serializer is not overridden then core creates two `MapSerializer` instances. First is initialized incorrectly (`keySerializer` is equal to `null`) and second which is initialized correctly.

When developer overrided the method, then only one serializer is created → that which is initialized incorrectly.

I created an example project here: https://github.com/agabrys/bugs-reports/tree/master/jackson-xml/empty-elements-serialization

https://github.com/agabrys/bugs-reports/blob/master/jackson-xml/empty-elements-serialization/v289/src/main/java/biz/gabrys/adam/bugsreports/jackson/xml/emptyelementsserialization/v289/SerializerModifierXmlSerializer.java
https://github.com/agabrys/bugs-reports/blob/master/jackson-xml/empty-elements-serialization/v289/src/test/java/biz/gabrys/adam/bugsreports/jackson/xml/emptyelementsserialization/v289/SerializerModifierXmlSerializerTest.java

Best Regards

**Comment by cowtowncoder** [comment]
This is commonly due to delegating serializer not implementing either `ResolvableSerializer` or `ContextualSerializer` -- especially latter is usually needed. These interfaces specify one method each, and they are needed to:

1. Handle recursive type definitions (and specifically circular ones, like class `A` that has field of type `B`, which in turn has a field of type `A`) -- this is what `ResolvableSerializer` is for
2. Give access to contextual information, mostly annotations that property has (which is not yet known when serializer for given type is requested).

In both cases you will want to delegate calls to the original `MapSerializer`; difference is simply that `resolve()` does not return anything (serializer itself is modified), whereas `createContextual()` returns either serializer it's called on, or a newly created instance. In latter case you need to construct new instance of your "wrapper" serializer with new delegate serializer.

`jackson-databind` has `StdDelegatingSerializer` which can be useful either as base class or to show typical implementation of these two methods.

I suspect that when you implement these 2 methods (and remember to implement interfaces) your problem will disappear.

**Comment by agabrys** [comment]
Thank you for the answer. I added:

    @Override
    public JsonSerializer<?> createContextual(SerializerProvider prov, BeanProperty property) throws JsonMappingException {
        if (serializer instanceof ContextualSerializer) {
            return ((ContextualSerializer) serializer).createContextual(prov, property);
        }
        return serializer;
    }

    @Override
    public void resolve(SerializerProvider provider) throws JsonMappingException {
        if (serializer instanceof ResolvableSerializer) {
            ((ResolvableSerializer) serializer).resolve(provider);
        }
    }

It solved the problem with the exception.

Sorry for delay but finally we decided to use JSON format instead of XML, because the same problem (missing `null` properties) exists for any objects (JSON does not have this restriction).
