### ISSUE TITLE
com.fasterxml.jackson.databind.exc.MismatchedInputException: no String-argument constructor/factory method to deserialize from String value

### ISSUE THREAD

**Issue by AnshikaKoul** [FasterXML/jackson-dataformat-xml#278]
Hi @cowtowncoder , 

My jackson version 2.9.3:

```
<jackson.version>2.9.3</jackson.version>
<dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version}</version>
</dependency>
<dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson.version}</version>
</dependency>
<dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
      <version>${jackson.version}</version>
</dependency>
<dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jdk8</artifactId>
      <version>${jackson.version}</version>
</dependency>
<dependency>
      <groupId>com.fasterxml.jackson.module</groupId>
      <artifactId>jackson-module-kotlin</artifactId>
      <version>${jackson.version}</version>
</dependency>
<dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-xml</artifactId>
      <version>${jackson.version}</version>
</dependency>
```
Kotlin version : ```<kotlin.version>1.2.10</kotlin.version>```
Ratpack version : ```<ratpack.kotlin.version>1.1.2</ratpack.kotlin.version>```

_I too am facing an issue while deserialising an element with an attribute._

Example XML that needs to be parsed :

```
<Something>
    <first cn="abc">someValue</first>
    <second>3050</second>
</Something>          
```

classes that I am using :

```
data class Something(
   @JacksonXmlProperty(localName = "first", namespace = somenamespace)  val first: String
   @JacksonXmlProperty(localName = "second", namespace = somenamespace)  val second: String
)
```
```
class ResponseXmlParser {
 private val xmlMapper = xmlObjectMapper()

  private val log = LoggerFactory.getLogger(javaClass)
  fun parseResponseXml(responseBodyStream: InputStream): Response {
    val jsonNode = xmlMapper.readValue(responseBodyStream, Envelope::class.java)
    log.info("RESPONSE: " + jsonNode.body.response)
    return jsonNode.body.response
  }

  private fun xmlObjectMapper(): XmlMapper {
    val jacksonXmlModule = JacksonXmlModule()
    jacksonXmlModule.setDefaultUseWrapper(false)

    return XmlMapper(jacksonXmlModule)
        .registerModule(KotlinModule())
        .registerModule(JavaTimeModule())
        .configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, false)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        .configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true) as XmlMapper
  }
}
```

Now in the first element that has both attribute value and textual content. whilst parsing I get this exception: 

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.order.soap.Something` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('3050')

which is really weird.  Coz I have other elements with just attribute value and all of them work just fine. Only this element which has both attribute value and textual content doesn't work.

I have also posted my comment here : which is related I guess https://github.com/FasterXML/jackson-dataformat-xml/issues/206

**Comment by cowtowncoder** [comment]
I think we would need a Java-only reproduction here. However: since `2.9.4` was just released earlier today, it might make sense to test against that as a first step?

**Comment by AnshikaKoul** [comment]
I did that already. but the error persists with 2.9.4 as well. Sigh. 

and If not here, then can you please let me know where should I report the kotlin deserialisation issues? :)

**Comment by AnshikaKoul** [comment]
and this is my xml parser:

```
class ResponseXmlParser {
 private val xmlMapper = xmlObjectMapper()

  private val log = LoggerFactory.getLogger(javaClass)
  fun parseResponseXml(responseBodyStream: InputStream): ShippingGuideResponse {
    val jsonNode = xmlMapper.readValue(responseBodyStream, Envelope::class.java)
    log.info("RESPONSE: " + jsonNode.body.shippingGuideResponse)
    return jsonNode.body.shippingGuideResponse
  }

  private fun xmlObjectMapper(): XmlMapper {
    val jacksonXmlModule = JacksonXmlModule()
    jacksonXmlModule.setDefaultUseWrapper(false)

    return XmlMapper(jacksonXmlModule)
        .registerModule(KotlinModule())
        .registerModule(JavaTimeModule())
        .configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, false)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        .configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true) as XmlMapper
  }
}
```

**Comment by cowtowncoder** [comment]
@AnshikaKoul I can not help with Kotlin side since I don't use Kotlin (nor am very knowledgeable, just read an intro or two). And as importantly, tests here (xml module) can not have dependency on Kotlin. This is why for me most useful thing would be to create equivalent of test in Java, model that is used with Scala as well, where applicable.

Now: adding a Kotlin issue would make sense except for one problem -- Kotlin module is unlikely to want dependency to XML module. Ideally the two would be orthogonal, as most bugs can be reproduced in either `jackson-databind` or either Kotlin or XML module (with dependency to databind), but do not require mixing of Kotlin and XML.

Looking at code I suspect I might be able to translate code, and with enough time will do that, as well. Unless someone beats me to it.

**Comment by AnshikaKoul** [comment]
hmm, will try to do that! 

and this is the entire stacktrace: 

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.soap.Product` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('3050')
 at [Source: (BufferedInputStream); line: 14, column: 47] (through reference chain: com.soap.Envelope["Body"]>com.soap.Body["Response"]->com.soap.Response["Consignments"]->com.soap.Consignments["Consignment"]->java.util.ArrayList[0]->com.soap.Consignment["Products"]->java.util.ArrayList[0]->com.soap.Products["Product"]->java.util.ArrayList[1])

at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1366)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:113)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:113)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:113)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
```

**Comment by AnshikaKoul** [comment]
hi @cowtowncoder 

I have the equivalent Java Code now, and I am able to replicate the error, which is good I guess. :) 

the dependencies that I have used for this : 

```
<dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.9.4</version>
</dependency>
```

_Java Version_ : Java8 
_Spring_ : ```<spring.version>4.3.13.RELEASE</spring.version>```

Java equivalent test of Kotlin!
```
@Test
    public void convertingKotlinToJava() throws IOException {
        XmlMapper xmlMapper = getXmlMapper();

        Something value = xmlMapper.readValue(
                        "<Something>" +
                                "<Products>" +
                                "<first cn=\"abc\">someValue</first>" +
                                "<second>3050</second>" +
                                "</Products>" +
                                "</Something>", Something.class);
        
System.out.println(value.getProducts().toString());
    }

    private XmlMapper getXmlMapper() {
        JacksonXmlModule jacksonXmlModule = new JacksonXmlModule();
        jacksonXmlModule.setDefaultUseWrapper(false);
        
        XmlMapper xmlMapper = new XmlMapper(jacksonXmlModule);
        xmlMapper.configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, false);
        xmlMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        xmlMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
        
        return xmlMapper;
    }
```

POJO: 

```
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlText;
import java.util.List;

public class Something {
    @JacksonXmlProperty(localName = "Products")
    private List<Products> products;

    public List<Products> getProducts() {
        return products;
    }
}

class Products {

    @JacksonXmlProperty(localName = "first")
    private String first;
    @JacksonXmlProperty(localName = "second")
    private String second;

    @Override
    public String toString() {
        return "First: "+first+"  Second: "+second;
    }
}
```

and the exception that I am getting on running that testCase is same that I get in Kotlin:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `no.request.Products` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('3050')
 at [Source: (StringReader); line: 1, column: 67] (through reference chain: no.request.Something["Products"]->java.util.ArrayList[1])

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:170)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:113)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
```

So if you try adding attribute to elements without any textual content say, `<Products>` or `<Something>` tag, then everything works fine. but adding to tag `<first>` or `<second>` elements which have both attribute value and textual content, well that doesn't work.

Hope this helps in looking at this issue :)

**Comment by cowtowncoder** [comment]
@AnshikaKoul Thank you very much for doing the investigation so far. And yes, yes it does help. XML module is challenging one, but fix by fix it is getting better. :)

**Comment by cowtowncoder** [comment]
One thing to note: I always suggest NOT adding this line:

```xmlMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);```

on test reproductions, unless it is essential part. It consistently hides relevant information on fail cases, and while there are reasons to sometimes use it in production systems, I feel it's more often harmful than helpful (and this is why it is not enabled by default).

Anyway, I will try to reproduce this now.

**Comment by cowtowncoder** [comment]
Ok, so this is not a bug but misconfiguration. Assumption here seems to be that Lists are expressed simply by repeating values: this is not how default Jackson handling works.
Instead, there has to be element for logical List-valued property, and that element then contains all values. So incoming XML content is missing `Products` tag (although wrapper name may be changed with `@@JacksonXmlElementWrapper` to something different too).

You can change this to use "unwrapped" style, in which repetition of element name works:

```
    @JacksonXmlElementWrapper(useWrapping = false)`
```

or alternatively change the global default:

```java
    xmlMapper.setDefaultUseWrapper(false);
```

Aside from this, the recommended way of troubleshooting problems like this is to first serialize contents (POJOs in question) to see what kind of structure Jackson expects to see -- the only guarantee given is that structure Jackson writes it can also read, not arbitrary XML. So in this question you would have seen the mismatch between expected and actual structures.

**Comment by cowtowncoder** [comment]
One more thing: Exception message given is cryptic, and I wish there was a way to improve that.
The point it is trying to convey is that it got a `String` value, and there's nothing in POJO to help deserializer it -- implies is the fact that it expects to see Object structure. If this was made clear, troubleshooting might be easier.

**Comment by AnshikaKoul** [comment]
@cowtowncoder : I am glad to be of help here :)  yeah it would be great when this is fixed, also in the meantime whilst the team works onto get this resolved, we can alteast try and improve how/what we throw as an exception here. imo it could be more explicit in stating what has gone wrong, like stating that this tag with an attribute and textual content is a problem here, or deserialisation has gone kaput because of tag <xyz aa="some">123</xyz> 🦉

coz the exception we get right now is a wee bit misleading! as you end up on a wild goose chase unearthing as to how could some random tags textual content be the problem here. but well, debugging this has been fun :-)

**Comment by AnshikaKoul** [comment]
ohh, didn't see your comments! let me go through it once.

**Comment by AnshikaKoul** [comment]
umm, if you see this aforementioned function: 

```
private XmlMapper getXmlMapper() {
        JacksonXmlModule jacksonXmlModule = new JacksonXmlModule();
        jacksonXmlModule.setDefaultUseWrapper(false);
        
        XmlMapper xmlMapper = new XmlMapper(jacksonXmlModule);
        xmlMapper.configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, false);
        xmlMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        xmlMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
        
        return xmlMapper;
    }
```

I am setting the `jacksonXmlModule.setDefaultUseWrapper(false);` as false. 🤔 

and even if I put as you suggested:

```
public class Something {
    @JacksonXmlElementWrapper(useWrapping = false, localName = "Products")
    @JacksonXmlProperty(localName = "Products")
    private List<Products> products;

    public List<Products> getProducts() {
        return products;
    }
}
```

I am still getting the aforementioned exception. So I doubt if this error is related to 

`@JacksonXmlElementWrapper(useWrapping = false, localName = "Products")`

**Comment by AnshikaKoul** [comment]
and I did find a work around in kotlin for this. though I could not make use of dataClasses for this. which is a shame. but nonetheless, like you mentioned this treats this tag as a POJO and not as a scalar value. 

so if I structure my POJO as this, it works. :

```
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlText;
import java.util.List;

public class Something {
    @JacksonXmlElementWrapper(useWrapping = false, localName = "Products")
    @JacksonXmlProperty(localName = "Products")
    private List<Products> products;

    public List<Products> getProducts() {
        return products;
    }
}

class Products {

    @JacksonXmlProperty(localName = "first")
    private First first;
    @JacksonXmlProperty(localName = "second")
    private String second;

    @Override
    public String toString() {
        return "First: "+first+"  Second: "+second;
    }
}

class First {
    @JacksonXmlProperty(localName = "cn", isAttribute = true)
    private String cn;

    @JacksonXmlText
    private String value;

    @Override
    public String toString() {
        return "[cn: "+cn+" value: "+value+"]";
    }
}
```

**Comment by AnshikaKoul** [comment]
but well. even if this workaround helps, this is what should be said in the exception, that a tag with textual content and attribute value will be treated as a POJO and not a scalar value. 

Like I said before, we can alteast try and improve how/what we throw as an exception here. imo it could be more explicit in stating what has gone wrong, like stating that this tag with an attribute and textual content is a problem here, or deserialisation has gone kaput because of tag <xyz aa="some">123</xyz> 🦉

coz the exception we get right now is a wee bit misleading! as you end up on a wild goose chase unearthing as to how could some random tags textual content be the problem here.

**Comment by AnshikaKoul** [comment]
@cowtowncoder : also, is the workaround I have done correct? is it the right way to go about it? 

Like, Jackson expecting an XML element with attributes and textual content  to be handled as a POJO, not scalar value. Is this the expected behaviour?

**Comment by cowtowncoder** [comment]
@AnshikaKoul Ah ok sorry, did miss `jacksonXmlModule.setDefaultUseWrapper(false);` part then. Perhaps I missed that as part of cut'n paste to try out the test case.

As to exception... exception message does not mean that element and attribute are considered String value... internally they are both converted as separate values. Rather what happens is that one "level" is consumed to match property (that is, excepted wrapping), and then one of String values is considered "the" value, instead of there being logical Object.

I am not saying error message gives that information in well-digestable form, btw, it is obscure. But deserializer only sees "translates" stream of tokens, from XML into `JsonToken` stream.
It is very difficult to piece together enough information because of this: databinding is explicit data-format agnostic, and has no visibility into XML specific aspects. So it is just streaming parser that knows all details, and it has to essentially map slightly different data model of XML into JSON.

Finally, on `@JacksonXmlText`. That is interesting, and to me also it seems unnecessary.
It is possible that it is due handling of `List`s, in unwrapped style, that leads to that.
I think your workaround does look legit; ideally I think both ways should work. But as things are, better to go with one that actually does work.

**Comment by AnshikaKoul** [comment]
hmm, oka.

**Comment by romanchekashov** [comment]
I use latest version of lib:
```
<dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.9.6</version>
        </dependency>
```
I've spent a lot of hours trying to fix this but it doesn't work for:
```
<Main>	
	<Something>
		<first cn="abc">someValue</first>
		<second>3050</second>
	</Something>          
	<Something>
		<first>someValue</first>
		<second>3050</second>
	</Something>          
</Main>
```
If you add:
```
class First {
    @JacksonXmlProperty(localName = "cn", isAttribute = true)
    private String cn;

    @JacksonXmlText
    private String value;

    @Override
    public String toString() {
        return "[cn: "+cn+" value: "+value+"]";
    }
}
```
it will throw exception for second element!
Both cases with and without attribute just doesn't work(
