### ISSUE TITLE
Deserializing map of arrays

### ISSUE THREAD

**Issue by jkubos** [FasterXML/jackson-dataformat-xml#313]
I am using Jackson, version 2.9.7. There is problem in deserialization of map of arrays. See following example:

```java
XmlMapper objectMapper = new XmlMapper();
		
Map<String, List<Integer>> origData = new HashMap<>();
origData.put("evenNumbers", Arrays.asList(2, 4, 6));
origData.put("oddNumbers", Arrays.asList(1, 3, 5));

System.out.println(origData);
		
String xml = objectMapper.writeValueAsString(origData);
		
System.out.println(xml);
		
Map<String, List<Integer>> roundtripData = objectMapper.readValue(xml, new TypeReference<Map<String, List<Integer>>>() {});
		
System.out.println(roundtripData);
```
It should convert map (with string key) of integer lists to XML and back.

I serializes objects into following XML:

```xml
<HashMap>
    <evenNumbers>2</evenNumbers>
    <evenNumbers>4</evenNumbers>
    <evenNumbers>6</evenNumbers>
    <oddNumbers>1</oddNumbers>
    <oddNumbers>3</oddNumbers>
    <oddNumbers>5</oddNumbers>
</HashMap>
```

And then fails during attempt to deserialize it:

```java
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: (StringReader); line: 1, column: 24] (through reference chain: java.util.LinkedHashMap["evenNumbers"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
	at com.navigo3.dryapi.test.Main.main(Main.java:45)
```

Can you please take a look? Thanks!

**Comment by cowtowncoder** [comment]
Use case of `List`s directly inside `Map`s (or any combinations) is not supported. This does not, and likely, will not, work.

**Comment by jkubos** [comment]
Oh, now I see there is long list of limitations: https://github.com/FasterXML/jackson-dataformat-xml#known-limitations

My use case is, that I have JSON based API where Jackson is extensively used. It would be nifty if I can switch between XML and JSON by just switching ObjectMapper and XmlMapper. So I will have to find other way. 

Thank you and closing this ticket.
