### ISSUE TITLE
Deserializing XML with POJO using @JacksonXmlText throws UnrecognizedPropertyException

### ISSUE THREAD

**Issue by kherrera-ebsco** [FasterXML/jackson-dataformat-xml#345]
### Version

- `com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.9`

### Issue

> It may be important to note that I use Lombok with Jackson, but I manually delombok'd the class and verified that it still throws the exception.

When a POJO uses `@JacksonXmlText`, deserialization is attempted on an empty field name instead of the field name. This results in the following exception to be thrown:

```
Unrecognized field "" (class BugTest$Example$ExampleBuilder), not marked as ignorable (2 known properties: "value", "name"])
 at [Source: (StringReader); line: 1, column: 37] (through reference chain: BugTest$Example$ExampleBuilder[""])
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "" (class BugTest$Example$ExampleBuilder), not marked as ignorable (2 known properties: "value", "name"])
 at [Source: (StringReader); line: 1, column: 37] (through reference chain: BugTest$Example$ExampleBuilder[""])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:274)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at BugTest.buggyTest(BugTest.java:30)
        ... snip ...
	at java.lang.Thread.run(Thread.java:748)
```

### MCVE

```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlText;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import org.junit.jupiter.api.Test;

public class BugTest {

    @Test
    public void buggyTest() throws Exception {
        XmlMapper mapper = new XmlMapper();

        mapper.registerModule(new Jdk8Module());
        mapper.setSerializationInclusion(Include.NON_EMPTY);

        Example in = Example
            .builder()
            .name("name")
            .value("value")
            .build();

        String xml = mapper.writeValueAsString(in);
        Example out = mapper.readValue(xml, Example.class);

        assertEquals(in.getName(), out.getName());
        assertEquals(in.getValue(), out.getValue());
        assertEquals(
            "<example name=\"name\">value</example>",
            xml
        );
    }

    @JacksonXmlRootElement(localName = "example")
    @JsonDeserialize(builder = Example.ExampleBuilder.class)
    public static class Example {

        @JacksonXmlProperty(isAttribute = true)
        private String name;

        @JacksonXmlText
        private String value;

        public static ExampleBuilder builder() {
            return new ExampleBuilder();
        }

        public String getName() {
            return name;
        }

        public String getValue() {
            return value;
        }

        @JsonPOJOBuilder(withPrefix = "")
        public static class ExampleBuilder {
            private String name;
            private String value;

            public Example build() {
                Example example = new Example();

                example.name = name;
                example.value = value;

                return example;
            }

            public ExampleBuilder name(String name) {
                this.name = name;

                return this;
            }

            public ExampleBuilder value(String value) {
                this.value = value;

                return this;
            }
        }
    }
}
```

**Comment by kherrera-ebsco** [comment]
I have worked around the issue by creating a custom deserializer to handle the no-name field. The deserializer also works with JSON deserializing since JSON deserializing works properly. Hopefully this can be a clue on where things are going wrong in Jackson.

```java
/**
 * A bug workaround for Jackson.
 */
public static class ExampleDeserializer extends StdDeserializer<Example> {

    public ExampleDeserializer() {
        this(null);
    }

    public ExampleDeserializer(Class<?> valueType) {
        super(valueType);
    }

    @Override
    public Example deserialize(JsonParser parser, DeserializationContext context)
        throws IOException {
        JsonNode node = parser.getCodec().readTree(parser);

        String name = null;
        String value = null;

        if (node.has("name")) {
            name = node.get("name").asText();
        }

        // Support XML.
        if (node.has("")) {
            value = node.get("").asText();

        // Support JSON.
        } else if (node.has("value")) {
            value = node.get("value").asText();
        }

        return Example
            .builder()
            .name(name)
            .value(value)
            .build();
    }
}
```

**Comment by cowtowncoder** [comment]
Actually the problem with test case is the assumption that annotations from value class `Example` would be used for the builder for deserialization: this is not the case; there is no binding.
So what is needed is adding annotation like so:

```
            @JacksonXmlText
            public ExampleBuilder value(String value) { }
```

and the test passes against 2.12 branch (for upcoming 2.12.0).
I'll add passing test.

**Comment by cowtowncoder** [comment]
Marked as resolved as the solution is to annotate "xml text" aspect on Builder.
