### ISSUE TITLE
Library picks wrong XMLStreamWriter?

### ISSUE THREAD

**Issue by mkpaz** [FasterXML/jackson-dataformat-xml#370]
Sorry, the title somewhat non-descriptive, but I'm unsure what really happens. I faced the same issue that already was reported (and closed) [here](https://github.com/FasterXML/jackson-jaxrs-providers/issues/20). More precisely I get this error when just trying to write object into file.

```
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Underlying Stax XMLStreamWriter (of type com.sun.xml.internal.stream.writers.XMLStreamWriterImpl) does not implement Stax2 API natively and is missing method 'writeRaw': this breaks functionality such as indentation that relies on it. You need to upgrade to using compliant Stax implementation like Woodstox or Aalto
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator._reportUnimplementedStax2(ToXmlGenerator.java:1325)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeRaw(ToXmlGenerator.java:772)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.util.DefaultXmlPrettyPrinter$Lf2SpacesIndenter.writeIndentation(DefaultXmlPrettyPrinter.java:528)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.util.DefaultXmlPrettyPrinter.writeStartObject(DefaultXmlPrettyPrinter.java:195)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeStartObject(ToXmlGenerator.java:521)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:113)
        at com.fasterxml.jackson.databind@2.10.0.pr3/com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind@2.10.0.pr3/com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind@2.10.0.pr3/com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind@2.10.0.pr3/com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:202)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
        at com.fasterxml.jackson.dataformat.xml@2.10.0.pr3/com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:107)
        at com.fasterxml.jackson.databind@2.10.0.pr3/com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
        at com.fasterxml.jackson.databind@2.10.0.pr3/com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3342)
        at example@1.0-SNAPSHOT/org.example.Main.main(Main.java:21)
```

What matters that this exception only happens when I launch app from JLink generated runtime image, and it's all fine if I run it from IDE (via exec or javafx plugin).

Here is minimal reproducible example: https://github.com/mkpaz/jackson-xml. Build like `mvn package -P build` and launch `target/runtime-images/win/bin/run.bat` and you'll get mentioned error. Use `mvn compile exec:java` and all will work as expected.

I use Bellsoft Liberica as OpenJDK vendor, because it comes with bundled OpenJFX.

**Comment by cowtowncoder** [comment]
First quick note: do NOT use 2.10.0.pr3. That is a pre-release version. Instead use official 2.10.0.
(I know, some systems may unfortunately consider 2.10.0.pr3 to be "later" than 2.10.0; we will change version naming scheme for later minor versions).

**Comment by mkpaz** [comment]
Thanks, it's ok on 2.10.0.
You're correct, I've just copy-pasted version from Maven Central, thought it's the latest.
