### ISSUE TITLE
XML with repeating elements without wrapper

### ISSUE THREAD

**Issue by gurpiarbassi** [FasterXML/jackson-dataformat-xml#371]
I have xml consisting of repeating elements without a wrapper.

The xsd has:
```
xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="order">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="header"/>
                <xs:element ref="bookingCodeRecord" minOccurs="0" maxOccurs="unbounded"/>

..
...

and
<xs:element name="bookingCodeRecord">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="recordType"/>
                <xs:element ref="sequenceNumber"/>
                <xs:element ref="lineNumber"/>
                <xs:element ref="bookingCodeString"/>
                <xs:element ref="carrierName"/>
```

Sample xml

```
<bookingCodeRecord>
        <recordType>B</recordType>
        <sequenceNumber>0887291224</sequenceNumber>
        <lineNumber>30</lineNumber>
        <bookingCodeString>vs</bookingCodeString>
        <carrierName>OwnFleet OwnFleetNextday</carrierName>
    </bookingCodeRecord>
<bookingCodeRecord>
        <recordType>B</recordType>
        <sequenceNumber>0887291224</sequenceNumber>
        <lineNumber>30</lineNumber>
        <bookingCodeString>as</bookingCodeString>
        <carrierName>OwnFleet OwnFleetNextday</carrierName>
    </bookingCodeRecord>
```

I canot deserialise this. I get an error as follows:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.oms.dto.atg.BookingCodeRecord` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('B')
 at [Source: (StringReader); line: 85, column: 22] (through reference chain: com.oms.dto.atg.OrderTO["bookingCodeRecord"]->java.util.ArrayList[0])

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)

```

I imagine not having the wrapper element here is causing an issue. What do I do?

**Comment by cowtowncoder** [comment]
I would need bit more help here, specifically POJOs you are using to read into: XML alone is not enough, and Jackson does not use XML Schema for anything.

**Comment by cowtowncoder** [comment]
No reproduction; will need one, may be reopened with it.
