### ISSUE TITLE
Binding text content when it is not the last child

### ISSUE THREAD

**Issue by spln** [FasterXML/jackson-dataformat-xml#381]
Versions: 2.9.9 and 2.10.2

When binding the following XML: 
```xml
<VALIDATION_RULES>
  sensible
  <MAX_LENGTH>512</MAX_LENGTH>
</VALIDATION_RULES>
```

to the Bean: 
```java
public class ValidationRules {
  
    @JacksonXmlProperty(localName = "MAX_LENGTH")
    private Double maxLength;
    @JacksonXmlText
    private String textContent;

}
```

I got the following exception: 
```
java.io.IOException: Expected END_ELEMENT, got event of type 1
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream.skipEndElement(XmlTokenStream.java:209)
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser.nextToken(FromXmlParser.java:594)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.skipChildren(ParserMinimalBase.java:237)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1584)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242)
```

When the text data is localized as the last child node, it works properly:
```xml
<VALIDATION_RULES>
  <MAX_LENGTH>512</MAX_LENGTH>
  sensible
</VALIDATION_RULES>
```

**Comment by cowtowncoder** [comment]
This is unfortunately not supported usage: it is so-called "mixed content" where elements and CDATA are mixed. I am actually surprised that the other ordering works... I would not expect that to either.
I do not have plans to try to support this either so it is not a simple bug fix but a design limitation.
