### ISSUE TITLE
Something very weird

### ISSUE THREAD

**Issue by kuangye098** [FasterXML/jackson-dataformat-xml#388]
# Version
* com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.10.1

# Issue

```java

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "charge" (class com.kaisaglobal.tradercenter.ayers.entity.MultipleOrderTest), not marked as ignorable (one known property: "charges"])
 at [Source: (StringReader); line: 1, column: 103] (through reference chain: com.kaisaglobal.tradercenter.ayers.message.response.MultipleOrdersQueryResTestMessage["order"]->java.util.ArrayList[0]->com.kaisaglobal.tradercenter.ayers.entity.MultipleOrderTest["charge"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1192)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.kaisaglobal.tradercenter.ayers.util.MessageBodyUtil.parseToPojo(MessageBodyUtil.java:45)
	at com.kaisaglobal.tradercenter.ayers.util.CompressionUtilTest.testMultipleOrders1(CompressionUtilTest.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

```java

String multipleOrdersXmlString =
                "<message type=\"multi_order\" msgnum=\"4\">" +
                        " <order>" +
                        "    <charges>" +
                        "      <charge>" +
                        "        <name>" +
                        "          <eng>Commission</eng>" +
                        "          <big5>佣金</big5>" +
                        "          <gb>佣金</gb>" +
                        "        </name>" +
                        "        <amt>0</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>5</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>2.7</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>2</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>5</amt>" +
                        "      </charge>" +
                        "    </charges>" +
                        "  </order>" +
                        "  <order>" +
                        "    <charges>" +
                        "      <charge>" +
                        "        <name>" +
                        "          <eng>Commission</eng>" +
                        "          <big5>佣金</big5>" +
                        "          <gb>佣金</gb>" +
                        "        </name>" +
                        "        <amt>0</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>5</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>2.7</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>2</amt>" +
                        "      </charge>" +
                        "      <charge>" +
                        "        <name/>" +
                        "        <amt>5</amt>" +
                        "      </charge>" +
                        "    </charges>" +
                        "  </order>" +
                        "</message>";

XmlMapper xmlMapper = new XmlMapper();
xmlMapper.configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES,false);
xmlMapper.readValue(multipleOrdersXmlString ,MultipleOrdersQueryResTestMessage.class)

```

```java
@Data
@JacksonXmlRootElement(localName = "message")
public class MultipleOrdersQueryResTestMessage{
     @JacksonXmlProperty(localName = "msgnum",isAttribute = true)
     private Long msgnum;

    @JacksonXmlProperty(localName = "type",isAttribute = true)
    private Type type;

     @JacksonXmlElementWrapper(localName = "order")
     List<MultipleOrderTest> multipleOrderList;
}
```

```java
@Data
public class MultipleOrderTest {

    @JacksonXmlProperty(localName = "charge")
    @JacksonXmlElementWrapper(localName = "charges")
    private List<OrderChargesInfo> orderChargesInfos;
}
```

```java
@Data
public class OrderChargesInfo {
    @JacksonXmlElementWrapper(localName = "name")
    private ChargeName chargeName;
    private String amt;
}
```

```java
@Data
public class ChargeName {
    private String eng;
    private String big5;
    private String gb;
}
```

**Comment by cowtowncoder** [comment]
Suggestion for troubleshooting: please do NOT use:

    xmlMapper.configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES,false);

because doing so will often hide information. In this case, one problem is:

```java
     @JacksonXmlElementWrapper(localName = "order")
     List<MultipleOrderTest> multipleOrderList;
```

where field is not `public`, but no annotation like `@JacksonXmlProperty` to indicate it as property (although I think it is expected `@JacksonXmlElementWrapper` is enough).
I will file separate issue to make `@JacksonXmlElementWrapper` taken as marker too, but you may want to either change this field to `public`, or just add `@JacksonXmlProperty` on it in the meantime.

I will see if I find other problems.

**Comment by cowtowncoder** [comment]
Another suggestion: when trying to figure out why a complex XML structured can not be read, try first serializing (writing) structure from test object. This let's you see expected structure.
In this case this property

```
        @JacksonXmlElementWrapper(localName = "order")
        List<MultipleOrderTest> multipleOrderList;
```

uses wrapped style, and as declared would need 2 nested `order` entries: if adding those, reading succeeds.
But what you probably tried to do would be this:

```
        @JacksonXmlProperty(localName = "order")
        @JacksonXmlElementWrapper(useWrapping = false)
        List<MultipleOrderTest> multipleOrderList;
```

which means that entries should not use wrapping, and would read content as used in test.

I hope this helps.
