### ISSUE TITLE
XML reading breaks when there is Unicode whitespace between elements

### ISSUE THREAD

**Issue by t9t** [FasterXML/jackson-dataformat-xml#398]
When reading XML (using `XmlMapper#readValue`) which has Unicode whitespace (eg. [EN SPACE](https://www.compart.com/en/unicode/U+2002) or EM SPACE) between elements, Jackson throws an exception: `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "" (class ...), not marked as ignorable (one known property: "element"])`.

For example, the following two XMLs.

This works fine (normal space between `<Alice>` and `<bob>`):
```
<Alice> <bob>asdf</bob></Alice>
```

The following returns an error (EN SPACE, 0x2002, between `<Alice>` and `<bob>`):
```
<Alice> <bob>asdf</bob></Alice>
```

There is a lot of different topics to find on whitespace in XML, on how to parse/interpret it, caveats, XSDs to define how to teat it, etc. It looks like a lot of them conflict each other, and I wasn't able to determine exactly how to treat the above correctly according to the XML specification.

But my two main arguments on why the above should "just work" are:
- As a developer who just wants to parse some XML it is irrelevant to me whether the whitespace is used consists of spaces, tabs, or unicode whitespace
- JAXB parses the above correctly without errors

But I can also imagine a viewpoint where you strictly define that the only allowed whitespace are in the ASCII range and the rest is just treated as "garbage".

I tested using `jackson-databind` and `jackson-dataformat-xml` both at version `2.11.0`.

Please see this gist for a full JUnit4 test class showing this issue and also showing that it parses fine using JAXB: https://gist.github.com/t9t/d94cac06249381083b25f6442047bd16

Full exception stack trace from the `jacksonEnSpace` test in that code:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "" (class jacksonxml.XmlMapperWhitespaceTest$Alice), not marked as ignorable (one known property: "bob"])
 at [Source: (StringReader); line: 1, column: 14] (through reference chain: jacksonxml.XmlMapperWhitespaceTest$Alice[""])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at jacksonxml.XmlMapperWhitespaceTest.jacksonEnSpace(XmlMapperWhitespaceTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by cowtowncoder** [comment]
My understanding is that as per XML specification, only characters considered white space are:

```
[3] | S | ::= | (#x20 \| #x9 \| #xD \| #xA)+
```

at least in XML 1.0 section 2.3.3 (https://www.w3.org/TR/xml/#sec-common-syn) and it seems unchanged for 1.1 as well (https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-common-syn). 
One caveat is that XML 1.1 did the ill-conceived addition of 2 IBM-pushed linefeeds (0x85, 0x2028)
, as per:

https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-line-ends

but as I recall these are to be normalized by XML parser (Woodstox or another stax parser) and so xml dataformat would never see them.

Given this, I don't see formal requirement for having special handling here. I suspect this might be an implementation detail in JAXB -- if `Character.isWhitespace` (or `.isSpaceChar()`) returns true, perhaps that is how it is detected.

Having said all that, I am not necessarily opposed to making the change as it might be relatively straight-forward change to Jackson's determination of "blank" String. I just want to make sure where the requirement would stem from.

**Comment by t9t** [comment]
Honestly, my case is not so strong. I was changing an app's XML parser from JAXB to `XmlMapper` and got the above error in unit tests. It turned out an XML document in the test scope used in the tests contained some EN SPACEs which made me notice this issue. As a fix I just changed the document to use normal spaces instead. I don't know of any consumers of my APIs which actually use such Unicode whitespace.

What prompted me to register this issue was the fact that the old implementation of the app using JAXB did parse the file correctly and a cursory search didn't come up with any indication whether or not this should be supported.

But your links to the XML specs are quite convincing.

**Comment by cowtowncoder** [comment]
Ok that makes sense. I think I will close this in that case -- and reconsider if someone else encounters same problem.
