### ISSUE TITLE
2.12.0-rc1 regression: no default no-arguments constructor found

### ISSUE THREAD

**Issue by henrik242** [FasterXML/jackson-dataformat-xml#427]
I have this Kotlin object which parses an XML into a `data class`:
```
object XmlTool {

    @JvmStatic
    fun parseXml(xml: String?): Product {
        val xmlIn = XMLInputFactory.newInstance()
        val factory = XmlFactory(xmlIn)
        val xmlModule = JacksonXmlModule()

        val mapper = XmlMapper(factory, xmlModule).registerKotlinModule()

        return mapper.readValue(xml, Product::class.java)
    }

    data class Stuff(val str: String?)
    data class Product(val stuff: Stuff?)
}
```
Parsing this in Jackson 2.12.0-rc1 fails with `com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `jackson.xml.XmlTool$Stuff` (although at least one Creator exists): no default no-arguments constructor found`.  Jackson 2.11.3 works just fine:
```
class Jackson212MissingConstructorTest {

    @Test
    void fails_with_jackson_2_12() throws Exception {
        String xml = "<product><stuff></stuff></product>";

        Product product = XmlTool.parseXml(xml);

        assertEquals(new Product(null), product);
    }
}
```
The full exception is:
```
jackson.xml.Jackson212MissingConstructorTest > fails_with_jackson_2_12() 
    com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `jackson.xml.XmlTool$Stuff` (although at least one Creator exists): no default no-arguments constructor found
     at [Source: (StringReader); line: 1, column: 17] (through reference chain: jackson.xml.XmlTool$Product["stuff"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1590)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1215)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createUsingDefault(ValueInstantiator.java:248)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:275)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.getEmptyValue(BeanDeserializerBase.java:1027)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmptyString(StdDeserializer.java:322)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:271)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1480)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
        at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4568)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3523)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3491)
        at jackson.xml.XmlTool.parseXml(XmlTool.kt:19)
        at jackson.xml.Jackson212MissingConstructorTest.fails_with_jackson_2_12(Jackson212MissingConstructorTest.java:14)
```
Here's a test project: https://github.com/henrik242/jackson-xml-problem/tree/2-12-empty-constructor

**Comment by henrik242** [comment]
@cowtowncoder Have you seen this?  Looking forward to rc2 😄

**Comment by kupci** [comment]
@henrik242 To make sure this is categorized correctly, are you sure this should be here in jackson-dataformat-xml? Or should it go under jackson-module-kotlin?  
```
dependencies {
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:$jacksonVersion")
    implementation**("com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")**

    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
}
```

**Comment by cowtowncoder** [comment]
@henrik242 Had not noticed it. As per @kupci's comment I suspect this might not Kotlin-specific, so I'll try to see if I can reproduce with XML and Java.

**Comment by cowtowncoder** [comment]
Actually, no, I would need a plain Java reproduction -- I am guessing this may well be due to problem with `@JsonCreator` handling (properties vs delegating), and/or not using `@JacksonXmlText`.

Test itself could be added under `jackson-integration-tests` which can combine Kotlin and XML modules (neither of which is allowed to depend on each other, even for tests, since doing so would lead to cyclic dependency that's gnarly for builds).

**Comment by cowtowncoder** [comment]
Example works with Java definitions like:

```
    static class Stuff427 {
        String str;

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public Stuff427(String s) { str = s; }
    }

    static class Product427 {
        Stuff427 stuff;

        public Product427(@JsonProperty("stuff") Stuff427 s) { stuff = s; }
    }

    public void testEmptyIssue427() throws Exception
    {
        String xml = "<product><stuff></stuff></product>";
        Product427 product = MAPPER.readValue(xml, Product427.class);
        assertNotNull(product);
        assertNotNull(product.stuff);
        assertEquals("", product.stuff.str);
    }
```

and the distinction is that the outer POJO requires properties-based creator (since there is propert "stuff"), whereas inner POJO requires delegate-based as it must map straight from String value.

So I don't see a bug in XML format module, and suspect that challenge is that of annotating `Stuff` to delegate `String` value.

**Comment by henrik242** [comment]
@cowtowncoder Should I re-post this issue in the Kotlin module? Or add a PR to https://github.com/FasterXML/jackson-integration-tests ? Or maybe both?

**Comment by cowtowncoder** [comment]
@henrik242 I think I'll first transfer this to Kotlin module, for maintainers to see.
