### ISSUE TITLE
Getting Runtime Exception

### ISSUE THREAD

**Issue by akhettar** [FasterXML/jackson-dataformat-xml#439]
Hello there,

I am getting RuntimeException with the latest version of the Jackson-core when trying to read csv into JsonNode object  - see below stack trace snippet. When I inspect the CsvParser.java at line 187 I don't see DEFAULT_READ_CAPABILITIES defined anywhere. Can you please assist?

**Code snippet**

CsvSchema schema = CsvSchema.emptySchema().withHeader();
CsvMapper csvMapper = new CsvMapper();
JsonNode jsonNode = csvMapper.readerFor(JsonNode.class)
              .with(csvSchema)
                .readTree(new ByteArrayInputStream(bytes));

      `<dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
            <version>2.12.0</version>
            <type>bundle</type>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.0</version>
            <type>bundle</type>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.12.0</version>
            <type>bundle</type>
        </dependency>`

`java.lang.NoSuchFieldError: DEFAULT_READ_CAPABILITIES

	at com.fasterxml.jackson.dataformat.csv.CsvParser.<clinit>(CsvParser.java:187)
	at com.fasterxml.jackson.dataformat.csv.impl.CsvParserBootstrapper.constructParser(CsvParserBootstrapper.java:161)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory._createParser(CsvFactory.java:402)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:312)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:15)
	at com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1235)
`	

https://github.com/FasterXML/jackson-dataformat-xml/blob/3f2a22a00d5077a734e91137b34f737b1df6dd1f/src/main/java/com/fasterxml/jackson/dataformat/xml/deser/FromXmlParser.java#L46

**Comment by cowtowncoder** [comment]
(note: this seems to be about CSV format, not XML, will transfer).

You seem to have incompatible version of components (despite `pom.xml` suggesting they should be the same): minor versions need to match.
What seems likely is that `jackson-core` version is older than 2.12, but `jackson-dataformat-csv` and/or `jackson-databind` is 2.12.
If possible, try to see what actual dependency versions are. It might even be possible that deployment might have duplicates of some jars.
