### ISSUE TITLE
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Invalid white space character (0x5) in text to output (in xml 1.1, could output as a character entity)

### ISSUE THREAD

**Issue by vmisra2018** [FasterXML/jackson-dataformat-xml#472]
@cowtowncoder 
i am using  <jackson.version>2.12.1</jackson.version> for below dependencies in  pom.
The only new dependency which i started to use [for xml to json utiltly which i wrote] is jackson-dataformat-xml.
All other jacakson dependencies where already present.
```
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
           <groupId>com.fasterxml.jackson.core</groupId>
           <artifactId>jackson-annotations</artifactId>
           <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <artifactId>jackson-dataformat-xml</artifactId>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <version>${jackson.version}</version>
        </dependency>
```

In another project, dependent on ther above utility project, I am seeing below error  . 
The error goes away if I remove jackson-dataformat-xml depedency  and everything works fine in old way[but yes ,now i cannot use xml to json utility code  :anguished:]

```
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Invalid white space character (0x5) in text to output (in xml 1.1, could output as a character entity)
        at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwAsGenerationException(StaxUtil.java:51)
        at com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeString(ToXmlGenerator.java:639)
        at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:212)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:129)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.faterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanPropertyWriter.serializeAsField(XmlBeanPropertyWriter.java:145)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:212)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:129)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanPropertyWriter.serializeAsField(XmlBeanPropertyWriter.java:145)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:212)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:129)
        at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:103)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:287)
        ... 43 more
Caused by: java.io.IOException: Invalid white space character (0x5) in text to output (in xml 1.1, could output as a character entity)
        at com.ctc.wstx.api.InvalidCharHandler$FailingHandler.convertInvalidChar(InvalidCharHandler.java:56)
        at com.ctc.wstx.sw.XmlWriter.handleInvalidChar(XmlWriter.java:629)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:583)
        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:467)
        at com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeString(ToXmlGenerator.java:634)
        ... 63 more`
  
```      
   I searched and found something similar but doesn't not appear appealing solution.
   https://stackoverflow.com/questions/47421275/axis2-error-invalid-white-space-character-0x4-in-text-to-output
   
   The link says Woodstox may be issue. But I guess jackson-dataformat-xml [and Woodstox -looks like it is used by jackson-dataformat-xml internally] have something to do with it. 
Do we have an elegant solution of above  ?  or can we have a fix from jackson-dataformat-xml library?

**Comment by cowtowncoder** [comment]
I am bit confused -- is there an actual reason to try to output character with Unicode code of 0x05? That is invalid character in XML 1.0; and although -- as per message -- XML 1.1 allows inclusion as character entity, what is the purpose here?

In most cases such characters are accidentally included garbage and should be removed. So maybe the first step would be to identify what is producing this character, and why? It probably should be removed as part of input validation.

**Comment by vmisra2018** [comment]
@cowtowncoder This is a legacy application. The error was not when you remove jackson-dataformat-xml dependency .
This module calls another backend legacy application hosting xml SOAP services. (There are many) and is consumed by stubs in our module. So it is not inbound to module from UI where we can validate by UI code and fix this but rather coming as SOAP response from  this backend.  Since it has been for working for years and is coming because out module added this dependency it would be difficult to ask them . So was thinking if it can be done at our end (as this looks like is validation due to  woodstox?)

**Comment by cowtowncoder** [comment]
What I am saying is that it is necessary to first understand the problem. If the problem is invalid data, that should be addressed. I don't know what existing system did and if it just did not do validation properly; it could alternatively be that what Jackson XML module is incorrect. But this is not evident from things like stack traces: data, reproduction are needed.

**Comment by cowtowncoder** [comment]
One more note: this problem is not by Jackson XML format module itself but by Woodstox -- but probably something added in Woodstox, new version of which is probably specified by XML module. If so, downgrading Woodstox version would work around the issue.

Woodstox itself also has many configuration options, some of which dictate kind of validation it performs. I blogged about this:

https://cowtowncoder.medium.com/configuring-woodstox-xml-parser-woodstox-specific-properties-1ce5030a5173

so that might help.

Other than this I don't see anything XML module could do.

Alternatively if XML module handling has issues, a full unit test would be needed to show a reproduction of the problem.

**Comment by vmisra2018** [comment]
Hi @cowtowncoder 
Thanks, I am going to try this. I did not have chance to replicate it by sample and upload to github as it was little time consuming to know incoming xml and what is happening. So I did not use this library(in legacy project) which I eagerly wanted.
I will also try to get a sample.

**Comment by cowtowncoder** [comment]
@vmisra2018 sounds good!
