### ISSUE TITLE
java.lang.NoSuchMethodError exception

### ISSUE THREAD

**Issue by anujkgarg** [FasterXML/jackson-dataformat-xml#486]
I have added below dependencies in pom.xml file - 
       

```
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.12.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.12.3</version>
            <scope>provided</scope>
        </dependency>

```

And added below code to read XML `data` - 

```
       XmlMapper xmlMapper = new XmlMapper();
        // Reads from XML and converts to POJO
        MyClass mycls = xmlMapper.readValue(data, MyClass.class);

        // Reads from POJO and converts to XML
        xmlMapper.writeValue(new File("test.xml"), mycls);
```
The XmlMapper() is throwing exception - 

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:176)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:145)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:127)
```

As per the [issue#471](https://github.com/FasterXML/jackson-dataformat-xml/issues/471), it can be resolved if all Jackson components have the same version. But still it is not working. Any clue please ?

**Comment by anujkgarg** [comment]
It works after Invalidate caches/Restart IntelliJ. Hence closing the ticket.
