### ISSUE TITLE
Provider for javax.xml.stream.XMLOutputFactory cannot be found

### ISSUE THREAD

**Issue by javadevtush** [FasterXML/jackson-dataformat-xml#521]
JDK 11
Spring - 5.3.19
SpringBoot - 2.6.7
Jackson Core - 2.13.2
Jackson DataBind - 2.13.2.2

**Jackson DataFormat XML Problematic version - 2.13.2** (Version 2.13.1 does not cause this issue)

_Caused by: javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLOutputFactory cannot be found
	at javax.xml.stream.FactoryFinder.find(Unknown Source) ~[?:?]
	at javax.xml.stream.XMLOutputFactory.newFactory(Unknown Source) ~[?:?]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:124) ~[jackson-dataformat-xml-2.13.2.jar!/:2.13.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:101) ~[jackson-dataformat-xml-2.13.2.jar!/:2.13.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:92) ~[jackson-dataformat-xml-2.13.2.jar!/:2.13.2]
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:141) ~[jackson-dataformat-xml-2.13.2.jar!/:2.13.2]
	at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder$XmlObjectMapperInitializer.create(Jackson2ObjectMapperBuilder.java:911) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:669) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter.<init>(MappingJackson2XmlHttpMessageConverter.java:52) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:104) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.web.filter.FormContentFilter.<init>(FormContentFilter.java:61) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.boot.web.servlet.filter.OrderedFormContentFilter.<init>(OrderedFormContentFilter.java:29) ~[spring-boot-2.6.7.jar!/:2.6.7]
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration.formContentFilter(WebMvcAutoConfiguration.java:179) ~[spring-boot-autoconfigure-2.6.7.jar!/:2.6.7]_

**Comment by cowtowncoder** [comment]
I would need a reproduction (sample project) to help here.

The expection message suggest that you do not have a Stax (javax.xml.stream) implementation: this is odd as `jackson-dataformat-xml` specifically does add Woodstox as dependency in `pom.xml`:

```
    <dependency>
      <groupId>com.fasterxml.woodstox</groupId>
      <artifactId>woodstox-core</artifactId>
      <version>6.2.7</version>
    </dependency>
```

However: you should probably ask help on Spring Boot forums as it is likely this has something to do with the issue.

I do not see anything different in dependency declarations between 2.13.1 and 2.13.2, for what that is worth.

**Comment by cowtowncoder** [comment]
Cannot reproduce; not sure this is a Jackson side issue. May be reopened with more information or -- ideally -- reproduction.

**Comment by jimmykane** [comment]
After updating from 2.12.1 to 2.13.1 we experienced a similar issue 

```
No static method newFactory(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljavax/xml/stream/XMLInputFactory; in class Ljavax/xml/stream/XMLInputFactory; o
``` 

@cowtowncoder  maybe something we forgot to change ?

**Comment by jimmykane** [comment]
Deps are 

```
implementation("com.google.android.material:material:1.5.0")
                implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.2")
                implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2")
                implementation("javax.xml.stream:stax-api:1.0-2")

```

**Comment by cowtowncoder** [comment]
@jimmykane Sounds like a version incompatibility. I would suggest trying dropping dependency of `"javax.xml.stream:stax-api:1.0-2"` since this API is part of JDK at this point and that dependency could conflict.
