### ISSUE TITLE
Jackson fails to instantiate class when only text node is present

### ISSUE THREAD

**Issue by codemonstur** [FasterXML/jackson-dataformat-xml#608]
The following code generates an exception:
```
public class JacksonBug {

    public static final String XML_WORKS_1 = """
            <root>
                <nested>
                    <other>text</other>
                    The text node.
                </nested>
            </root>
            """;
    public static final String XML_WORKS_2 = """
            <root>
                <plain>The text node.</plain>
            </root>
            """;
    public static final String XML_FAILS = """
            <root>
                <nested>The text node.</nested>
            </root>
            """;

    private static class Root {
        public Nested nested;
        public Plain plain;
    }
    private static class Nested {
        @JacksonXmlProperty(isAttribute = false)
        public String other;
        @JacksonXmlProperty(isAttribute = false)
        public String reallyNotHere;
        @JacksonXmlText
        public String text;
    }
    private static class Plain {
        @JacksonXmlText
        public String text;
    }

    public static void main(final String... args) throws JsonProcessingException {
        final var xmlMapper = new XmlMapper();
        xmlMapper.readValue(XML_WORKS_1, Root.class);
        xmlMapper.readValue(XML_WORKS_2, Root.class);
        xmlMapper.readValue(XML_FAILS, Root.class);
    }

}
```
Setting fields to private or public has no effect. If I add the <other> tag the parsing works fine. If I remove the other and reallyNotHere fields the parsing works fine. But when the child tags are NOT there and the field IS there I get this Exception:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `tools.JacksonBug$Nested` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('The text node.')
 at [Source: (StringReader); line: 2, column: 27] (through reference chain: tools.JacksonBug$Root["nested"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1739)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1364)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at tools.JacksonBug.main(JacksonBug.java:50)

Process finished with exit code 1
 ```

Jackson version: 2.15.2

**Comment by pjfanning** [comment]
Have a look at these search results - https://github.com/search?q=repo%3AFasterXML%2Fjackson-dataformat-xml%20JsonIgnore&type=code

The JsonIgnore annotation and variants of it are what are used in Jackson to ignore fields.

**Comment by codemonstur** [comment]
> Have a look at these search results - https://github.com/search?q=repo%3AFasterXML%2Fjackson-dataformat-xml%20JsonIgnore&type=code
> 
> The JsonIgnore annotation and variants of it are what are used in Jackson to ignore fields.

I don't want to ignore the field. This is a very real field that is sometimes there and sometimes not there. And I need access to the value inside it if it is there.

**Comment by pjfanning** [comment]
This looks like the correct behaviour to me. You have a mechanism to get this to work (the `XmlElement ` annotation).
We can't just go and change Jackson behaviour - other users depend on it working the way that it does already. Even if we decide to change it to suit you then you will need to wait for a release.

In the end of the day, you have to accept that libs work a certain way. Jackson is very pluggable - write your own custom deserializer if you don't like the built-in behaviour. Or there are dozens of alternative libs for deserializing XML.

**Comment by codemonstur** [comment]
No this is definitely not correct behavior. And as far as I can tell there is no way to configure the class to get the data to parse. Just to be clearer on what can happen here, these are both valid XML snippets:
```
<root>
  <nested>
       <subtag>somedata</subtag>
        A text node
   </nested>
</root>

<root>
   <nested>A text node</nested>
</root>
```
Both should be parsable using a single class that contains one @XmlElement annotated field and one @XmlValue. The second snippet should simply call the default contructor and leave the field to null. Dieing with an error on this input is very much not correct. Fields are allowed to be null, that is normal behavior everywhere else, it is just here where Jackson fails.

**Comment by pjfanning** [comment]
Can you find the docs that describe that the code is supposed to work the way you want? If not, then this is not a bug - it is a change request.

**Comment by codemonstur** [comment]
I'm not interested in a debate over semantics or what rules have been defined somewhere. If you wish to call it a change request instead of a bug thats fine by me. At the moment I see no way to write a set of classes that can be used to parse the above two snippets. And both snippets are valid XML and structurally similar. I'm fine with an alternative configuration using whatever settings in Jackson, field naming, classes, or annotations may exists. I just want access to my data.

**Comment by pjfanning** [comment]
Write a custom deserializer if you can't get it to work with the default jackson-dataformat-xml code. There are examples online of how to write Jackson custom deserializers. Or try another XML lib.

Jackson is a JSON lib that has some support for other formats. There is no great community around jackson-dataformat-xml. It is what it is. Even if someone feels the need to do something on this issue, it could be weeks, months or years until that happens.

**Comment by cowtowncoder** [comment]
Quick note on POJO: you are declaring private (and, `final`...) fields besides no-args constructor -- how would values be expected to be passed to `Nested` class?

**Comment by codemonstur** [comment]
> Quick note on POJO: you are declaring private (and, `final`...) fields besides no-args constructor -- how would values be expected to be passed to `Nested` class?

The classes are marked with the @XmlAccessorType(FIELD) annotation which instructs the serializer to set the fields directly instead of going through a constructor or setter. I prefer this way since there is less code and it makes it clear to the reader that these classes are immutable DTOs and only set through serialization.

> But other than that, handling Mixed Content (both XML Text and XML Element(s) at same level) is very difficult for data-binding. It is possible some cases may not be supportable.

The configuration is unambiguous and works well in all other circumstances. If the child tag exists Jackson can parse the XML just fine. The @XmlValue annotation is being used the way it should and Jackson clearly supports it. And if the child tag isn't there the field could be set to null, the same way a field is normally set to null when a tag is absent.
 
> Still, what would help here would be fail reproduction using only Jackson annotations (use of JAXB annotations for actual use is fine, but for unit tests we ideally need Jackson equivalents). This would eliminate possibility of issue being due to JAXB annotation support (and if so, moving issue there) and avoid problem with cross module dependencies (XML module does not depend on JAXB annotation support).

I want it to work with JAXB annotations (for reasons..). That said, I automatically assumed it would be the parser itself where the problem lies instead of the annotation project. Should I create another bug report at `com.fasterxml.jackson.module:jackson-module-jaxb-annotations`?

**Comment by cowtowncoder** [comment]
No need to create/move issue, but the test case really needs to use Jackson annotations. This should be fine as there are equivalents.

But on fields: Jackson does not recognize or use `@XmlAccessorType` annotation. Use of `@XmlElement` etc, however, does make Jackson discover fields -- but they should not be `final` as final fields should not be settable outside of constructors. So all that needs to change for test is to keep them non-final.

I don't think either of these things is the root cause of the issue.

**Comment by codemonstur** [comment]
@cowtowncoder You are right JAXB was an unnecessary complication. The same problem exists when using just jackson annotations and the standard XmlMapper. To make you happy I also removed the finals :). I edited the original question at the top with the new code.

**Comment by cowtowncoder** [comment]
Thank you @codemonstur
