### ISSUE TITLE
Jackson Serializer The prefix for attribute associated with an element type is not bound.

### ISSUE THREAD

**Issue by jeacott** [FasterXML/jackson-dataformat-xml#67]
I get this exception when I try to call xmlMapper.writeValueAsString(...)
*it works as expected if I use the json ObjectMapper instead.

the serializer is creating xml, but not declaring a namespace

the offending field in the object being serialized seems to be
private List<Element> elements;

; Line#: 1; Column#: 162
javax.xml.transform.TransformerException: The prefix "zdef-1268121660" for attribute "zdef-1268121660:_class" associated with an element type "elements" is not bound.
    at org.apache.xalan.transformer.TransformerImpl.fatalError(TransformerImpl.java:744)
    at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:720)
    at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1192)
    at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1170)
    at au.gov.sa.pir.ebiz.emp.ui.validation.OutputTests.fopTest1(OutputTests.java:139)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at

**Comment by aphilip** [comment]
You can also do this:
    `xmlMapper.getFactory().getXMLOutputFactory().setProperty("javax.xml.stream.isRepairingNamespaces`

**Comment by cowtowncoder** [comment]
@aphilip When relying on default output factory, this should be done automatically.

**Comment by kareemjeiroudi** [comment]
Thanks a lot for following up on this! It resolved my issue. I tried the second solution
```java
xmlMapper.getFactory().getXMLOutputFactory().setProperty("javax.xml.stream.isRepairingNamespaces", true);
```
I wasn't able to try the solution in the first StackOverflow answer, because we are working on a project where you we can't easily add/removed dependencies.

**Comment by cowtowncoder** [comment]
@kareemjeiroudi Glad you were able to get it working. This is bit odd just because writer should do that for you, but maybe `XMLStreamWriter` was passed as-is, in which case caller is assumed to do it.

**Comment by weichaen** [comment]
I can't do this 
`xmlMapper.getFactory().getXMLOutputFactory()`
beacuse this is no `XMLOutputFactory()` in this Class
